<?php
namespace backend\models;
use yii\db\ActiveRecord;

class Information extends ActiveRecord{
    public $password;
    //常量定义场景
    const SCENARIO_Add ='add';
    public function rules()
    {
        return [
            [['name','type','username'],'required'],
            ['password','required','on'=>self::SCENARIO_Add]
        ];
    }

    public function attributeLabels()
    {
        return [
            'name'=>'名称',
            'type'=>'类别',
            'username'=>'用户名',
            'password'=>'密码',
        ];
    }

    public function beforeSave($insert)
    {
        if($insert){
            //添加管理员
            $this->password_hash=\Yii::$app->security->generatePasswordHash($this->password);//对提交过来的加密
            $this->create_time=time();//生成添加时间
            $this->auth_key=\Yii::$app->security->generateRandomString();//生成自动登录密钥(随机字符串)
        }else{
            //修改管理员
            if($this->password){
                //如果没有填写修改密码,就不修改密码
                $this->password_hash=\Yii::$app->security->generatePasswordHash($this->password);//对提交过来的加密
            }
            $this->update_time=time();//生成添加时间
            $this->auth_key=\Yii::$app->security->generateRandomString();//生成自动登录密钥(随机字符串)

        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}